### ISSUE TITLE
我想您可以考慮既有的部署工具

### ISSUE THREAD

**Issue by kanasimi** [lovelyCARDINAL/mgp-cewbot#1]
我在 Toolforge 上已做了自動化部署於更新工具
或許您可以考慮採用這個工具
就不用擔心更新與相容問題了

**Comment by lovelyCARDINAL** [comment]
我并不了解如何进行自动化部署和工作，请您指教！
toolforge那边是要如何操作？之前开了个[新的tool](https://toolsadmin.wikimedia.org/tools/id/mgp-cewbot)倒是。

**Comment by lovelyCARDINAL** [comment]
> 我在 Toolforge 上已做了自動化部署於更新工具 或許您可以考慮採用這個工具 就不用擔心更新與相容問題了

我并不了解如何进行自动化部署和工作，请您指教！
toolforge那边是要如何操作？之前开了个[新的tool](https://toolsadmin.wikimedia.org/tools/id/mgp-cewbot)倒是。

**Comment by kanasimi** [comment]
已經部署好了。請編輯 `~/wikibot/wiki\ configuration.js`

**Comment by lovelyCARDINAL** [comment]
> 已經部署好了。請編輯 `~/wikibot/wiki\ configuration.js`

Done.
但我想知道如何正式启用它。

**Comment by kanasimi** [comment]
您可參考 `crontab -e` 裡面的排程工作

我剛剛試了一下 還是有 403 的問題
您可以參考 `~/cron-*` 檔案的紀錄
感覺還是WAF的問題?

**Comment by lovelyCARDINAL** [comment]
WAF的问题应该解决了，把185.16.56.1放在白名单了，不知道为何之前185.16.56.0/23没有生效。
现在.1和.66在白名单

编辑好像没有什么好办法
或许可以把设定写在github当前仓库的某个页面，然后使用机器人把设定同步到userjson页面?
或者通过其他IM（如果方便提供的话）联系leranjun或者我，leranjun在海外，可能更方便

**Comment by kanasimi** [comment]
> 或许可以把设定写在github当前仓库的某个页面，然后使用机器人把设定同步到userjson页面?
這個不錯 我有時間再試試

我嘗試跑了一下
現在沒被擋了 
不過出現了這個問題
login [星海-adminbot@cewbot] failed 1/2: [Failed] Incorrect username or password entered. Please try again. (https://zh.moegirl.org.cn/api.php)
@lovelyCARDINAL 可能要麻煩您確認一下

**Comment by lovelyCARDINAL** [comment]
我改好了，可能是因为刚刚调整了机器人权限导致密码被重置了

**Comment by kanasimi** [comment]
您試過這個也有問題嗎
`cat ~/cron-20170915.topic_list.moegirl.*`

另外我還是登入不進去 
不曉得和中文有沒有關係
我可能要研究一下...

**Comment by kanasimi** [comment]
@lovelyCARDINAL 剛剛測試的時候出了問題 麻煩請撤銷這一頁的編輯 謝謝 [萌娘百科 talk:讨论版/群组信息](https://zh.moegirl.org.cn/%E8%90%8C%E5%A8%98%E7%99%BE%E7%A7%91_talk:%E8%AE%A8%E8%AE%BA%E7%89%88/%E7%BE%A4%E7%BB%84%E4%BF%A1%E6%81%AF)

**Comment by lovelyCARDINAL** [comment]
刚刚看了一下，似乎还有同步错位的问题。将操作申请的topiclist写在了页面相关，将群组信息的topiclist写到了方针政策。

**Comment by kanasimi** [comment]
等最近有時間測試看看...

**Comment by lovelyCARDINAL** [comment]
> 您試過這個也有問題嗎 `cat ~/cron-20170915.topic_list.moegirl.*`

可以，但发现了一个问题
`All 5 bureaucrats confirmed`输出的内容有误，实际输出的是监督员(`suppress`)而不是行政员(`bureaucrats`)

**Comment by kanasimi** [comment]
問題解決了
不知為何
wikibot/
底下又安裝了一個舊版的 node_modules/
現在已經回復正常了
準備把功能上線

**Comment by lovelyCARDINAL** [comment]
> 準備把功能上線
自动存档萌娘百科讨论版的功能大概可以移除了，AnnAngela-abot早已替代此任务。
另外我没找到锚点修复后悬挂即将删除模板那一部分的代码，现在大概不需要这个，可以执行删除了。

**Comment by kanasimi** [comment]
> 锚点修复后悬挂即将删除模板那一部分的代码，现在大概不需要这个，可以执行删除了。

刪除功能要再寫一下...

**Comment by kanasimi** [comment]
刪除功能上線了 還要麻煩您看一下狀況 謝謝

**Comment by lovelyCARDINAL** [comment]
> 將action_for_blank_talk_page的內容改成`DELETE` 

改了。
但似乎因为昨晚添加删除权限后机器人密码被重置，我没有及时在toolforge更新，导致机器人频繁登录失败，被阻止登录2天。
暂不知道运维方在后台能不能解除这个限制。

**Comment by kanasimi** [comment]
了解

**Comment by lovelyCARDINAL** [comment]
> 刪除功能上線了

我想问一下删除的原因是哪里设定的？

**Comment by kanasimi** [comment]
> 我想问一下删除的原因是哪里设定的？

https://github.com/kanasimi/wikibot/commit/e7bbe1077335dcf1c24061f46472c1e970f2ecc7

**Comment by leranjun** [comment]
> [kanasimi/wikibot@e7bbe10](https://github.com/kanasimi/wikibot/commit/e7bbe1077335dcf1c24061f46472c1e970f2ecc7)

L1130`wiki.delete`操作留在日志里的原因是什么？

**Comment by lovelyCARDINAL** [comment]
> 被阻止登录2天。

应该到期了，但似乎没有动静，是因为设定页需要调整到U:星海-adminbot的子页面吗？
此前部分err日志太长我作了删除处理。

**Comment by kanasimi** [comment]
沙盒的程式需要調整

基本上log手動清還是會一直增加

**Comment by kanasimi** [comment]
萌娘百科上原cewbot的功能應該已經復原了
若有問題請到 [kanasimi/wikibot](https://github.com/kanasimi/wikibot) 提出議題

**Comment by lovelyCARDINAL** [comment]
> 萌娘百科上原cewbot的功能應該已經復原了 萌娘百科的沙盒[似乎有點多](https://zh.moegirl.org.cn/User:%E6%9C%BA%E5%A8%98%E9%AC%BC%E5%BD%B1233%E5%8F%B7) 

是，我和鬼影233交流过了。
剩下的2个沙盒（module:Sandbox/test、help:沙盒/json）基本没人用所以一般不需要清理。

**Comment by lovelyCARDINAL** [comment]
@kanasimi  想问一下 20210429.Auto-archiver.js 具体是做什么的，我看排程里面每天4点18分(CST)有自动执行，但是似乎没有产生实际作用。

**Comment by kanasimi** [comment]
自動存檔嵌入{{Auto-archive}}的頁面。

另外新議題麻煩請開新的一串

**Comment by lovelyCARDINAL** [comment]
感谢答复
