### ISSUE TITLE
cron-update.wikibot 出错

### ISSUE THREAD

**Issue by lovelyCARDINAL** [lovelyCARDINAL/mgp-cewbot#2]
@kanasimi 我不太明白这个问题是要怎么解决，麻烦您检查了
`Traceback (most recent call last):  File "/usr/bin/jsub", line 797, in `
`    main() `
` File "/usr/bin/jsub", line 678, in main `
`   args = parse_script_comments(args)`
`  File "/usr/bin/jsub", line 659, in parse_script_comments`
`    with open(namespace.program, "r", encoding="latin1") as fh:PermissionError: [Errno 13] Permission denied: '/data/project/signature-checker/wikibot/init.sh'`

**Comment by kanasimi** [comment]
fixed
