### ISSUE TITLE
bug 2022-09-21

### ISSUE THREAD

**Issue by lovelyCARDINAL** [lovelyCARDINAL/mgp-cewbot#3]
1. 清理沙盒任务似乎存在问题，导致至少3日没有正常运行此任务了，详见error log。
2. 补签名日志存档任务似乎也存在问题，返回`未知的 API 回應：{"warnings":{"main":{"*":"Unrecognized parameter: rvslots."}},"batchcomplete":""} `，不清楚是不是最近才有的问题。

麻烦您检查了 @kanasimi

**Comment by kanasimi** [comment]
清理沙盒任務已修正

補簽名任務再觀察看看

**Comment by lovelyCARDINAL** [comment]
> 清理沙盒任務已修正

感谢！

> 補簽名任務再觀察看看

不是补签名任务，是补签名的用户页记录的存档任务（

**Comment by kanasimi** [comment]
看來是因為萌娘百科版本比較舊的緣故... https://zh.wikipedia.org/w/api.php?action=help&modules=query%2Brevisions https://zh.moegirl.org.cn/api.php?action=help&modules=query%2Brevisions
