### ISSUE TITLE
关于k8s化

### ISSUE THREAD

**Issue by lovelyCARDINAL** [lovelyCARDINAL/mgp-cewbot#4]
今天萌娘百科恢复部分编辑了，机器人应该可以重新运行了
问问kanashimi佬这边有没有将cronjob改用k8s的计划

**Comment by kanasimi** [comment]
您指的是這個嗎?
https://wikitech.wikimedia.org/wiki/Help:Toolforge/Jobs_framework#Grid_Engine_migration

**Comment by lovelyCARDINAL** [comment]
对。
以及这个[https://techblog.wikimedia.org/2022/03/14/toolforge-and-grid-engine/](https://techblog.wikimedia.org/2022/03/14/toolforge-and-grid-engine/)

**Comment by kanasimi** [comment]
看來要費點時間測試才行

**Comment by kanasimi** [comment]
我這邊的任務太多
要做的話恐怕得寫個小工具轉移 
現在還懶得寫
有時間再說了

**Comment by lovelyCARDINAL** [comment]
辛苦了
